using System;
using System.Collections.Generic;
using System.Text;

namespace ALISS.STARS.DTO.NarstService
{
    public class NarstServiceDTO
    {
        public string country_a { get; set; }
		public string x_hos_code { get; set; }
		public string x_hos_name { get; set; }
		public string x_year { get; set; }
		public string laboratory { get; set; }
		public string region { get; set; }
		public string province { get; set; }
		public string district { get; set; }
		public string x_address { get; set; }
		public string origin { get; set; }
		public string x_idcard { get; set; }
		public string x_an { get; set; }
		public string patient_id { get; set; }
		public string first_name { get; set; }
		public string last_name { get; set; }
		public string sex { get; set; }
		public DateTime? date_birth { get; set; }
		public string age { get; set; }
		public string occupation { get; set; }
		public string nationalty { get; set; }
		public DateTime? date_admis { get; set; }
		public string x_refer { get; set; }
		public string nosocomial { get; set; }
		public string x_admis_spec { get; set; }
		public string clnoutcome { get; set; }
		public string diagnosis { get; set; }
		public DateTime? date_disch { get; set; }
		public string x_status { get; set; }
		public string department { get; set; }
		public string institut { get; set; }
		public string ward { get; set; }
		public string ward_type { get; set; }
		public string x_ref_no { get; set; }
		public string spec_num { get; set; }
		public DateTime? spec_date { get; set; }
		public string spec_type { get; set; }
		public string spec_code { get; set; }
		public string x_spec_ful { get; set; }
		public string organism { get; set; }
		public string x_org_full { get; set; }
		public string org_type { get; set; }
		public string esbl { get; set; }
		public string comment { get; set; }
		public string amk_nd30 { get; set; }
		public string amc_nd20 { get; set; }
		public string amp_nd10 { get; set; }
		public string sam_nd10 { get; set; }
		public string azm_nd15 { get; set; }
		public string czo_nd30 { get; set; }
		public string fep_nd30 { get; set; }
		public string cfm_nd5 { get; set; }
		public string csl_nd30 { get; set; }
		public string ctx_nd30 { get; set; }
		public string fox_nd30 { get; set; }
		public string caz_nd30 { get; set; }
		public string czx_nd30 { get; set; }
		public string cro_nd30 { get; set; }
		public string cxa_nd30 { get; set; }
		public string cxm_nd30 { get; set; }
		public string chl_nd30 { get; set; }
		public string cip_nd5 { get; set; }
		public string cli_nd2 { get; set; }
		public string dap_nd30 { get; set; }
		public string dor_nd10 { get; set; }
		public string etp_nd10 { get; set; }
		public string ery_nd15 { get; set; }
		public string fos_nd200 { get; set; }
		public string fus_nd10 { get; set; }
		public string gen_nd10 { get; set; }
		public string geh_nd120 { get; set; }
		public string ipm_nd10 { get; set; }
		public string lvx_nd5 { get; set; }
		public string mem_nd10 { get; set; }
		public string nal_nd30 { get; set; }
		public string net_nd30 { get; set; }
		public string nit_nd300 { get; set; }
		public string nor_nd10 { get; set; }
		public string ofx_nd5 { get; set; }
		public string oxa_nd1 { get; set; }
		public string pen_nd10 { get; set; }
		public string pip_nd100 { get; set; }
		public string tzp_nd100 { get; set; }
		public string pol_nd300 { get; set; }
		public string sth_nd300 { get; set; }
		public string str_nd10 { get; set; }
		public string tec_nd30 { get; set; }
		public string tcy_nd30 { get; set; }
		public string sxt_nd1_2 { get; set; }
		public string van_nd30 { get; set; }
		public string mno_nd30 { get; set; }
		public string tgc_nd15 { get; set; }
		public string spt_nd100 { get; set; }
		public string ctc_nd30 { get; set; }
		public string ccv_nd30 { get; set; }
		public string cep_nd30 { get; set; }
		public string mfx_nd5 { get; set; }
		public string amx_nd30 { get; set; }
		public string axs_nd { get; set; }
		public string rif_nd5 { get; set; }
		public string amb_nd10 { get; set; }
		public string vor_nd1 { get; set; }
		public string vio_nd { get; set; }
		public string pru_nd5 { get; set; }
		public string cpd_nd10 { get; set; }
		public string vam_nd { get; set; }
		public string fdc_nd { get; set; }
		public string ctp_nd30 { get; set; }
		public string cza_nd30 { get; set; }
		public string czt_nd30 { get; set; }
		public string imr_nd10 { get; set; }
		public string mev_nd20 { get; set; }
		public string ctx_nm { get; set; }
		public string ctx_ne { get; set; }
		public string caz_nm { get; set; }
		public string caz_ne { get; set; }
		public string czx_nm { get; set; }
		public string czx_ne { get; set; }
		public string cro_nm { get; set; }
		public string cro_ne { get; set; }
		public string chl_nm { get; set; }
		public string chl_ne { get; set; }
		public string cip_nm { get; set; }
		public string cip_ne { get; set; }
		public string cli_nm { get; set; }
		public string cli_ne { get; set; }
		public string col_nm { get; set; }
		public string col_ne { get; set; }
		public string dap_nm { get; set; }
		public string dap_ne { get; set; }
		public string etp_nm { get; set; }
		public string etp_ne { get; set; }
		public string ery_nm { get; set; }
		public string ery_ne { get; set; }
		public string ipm_nm { get; set; }
		public string ipm_ne { get; set; }
		public string mem_nm { get; set; }
		public string mem_ne { get; set; }
		public string net_nm { get; set; }
		public string net_ne { get; set; }
		public string pen_nm { get; set; }
		public string pen_ne { get; set; }
		public string van_nm { get; set; }
		public string van_ne { get; set; }
		public string azm_ne { get; set; }
		public string gen_nm { get; set; }
		public string gen_ne { get; set; }
		public string tcy_nm { get; set; }
		public string tcy_ne { get; set; }
		public string cxm_nm { get; set; }
		public string cfm_ne { get; set; }
		public string amp_nm { get; set; }
		public string amp_ne { get; set; }
		public string fep_nm { get; set; }
		public string fep_ne { get; set; }
		public string lvx_nm { get; set; }
		public string lvx_ne { get; set; }
		public string amk_nm { get; set; }
		public string amk_ne { get; set; }
		public string tzp_nm { get; set; }
		public string tzp_ne { get; set; }
		public string sam_nm { get; set; }
		public string sam_ne { get; set; }
		public string czo_nm { get; set; }
		public string czo_ne { get; set; }
		public string azm_nm { get; set; }
		public string cxm_ne { get; set; }
		public string cxa_nm { get; set; }
		public string cxa_ne { get; set; }
		public string amc_nm { get; set; }
		public string amc_ne { get; set; }
		public string csl_nm { get; set; }
		public string csl_ne { get; set; }
		public string oxa_nm { get; set; }
		public string oxa_ne { get; set; }
		public string fox_nm { get; set; }
		public string fox_ne { get; set; }
		public string nor_nm { get; set; }
		public string nor_ne { get; set; }
		public string geh_nm { get; set; }
		public string geh_ne { get; set; }
		public string tec_nm { get; set; }
		public string tec_ne { get; set; }
		public string fos_nm { get; set; }
		public string fos_ne { get; set; }
		public string nit_nm { get; set; }
		public string nit_ne { get; set; }
		public string sxt_nm { get; set; }
		public string sxt_ne { get; set; }
		public string dor_nm { get; set; }
		public string dor_ne { get; set; }
		public string mno_nm { get; set; }
		public string mno_ne { get; set; }
		public string spt_nm { get; set; }
		public string spt_ne { get; set; }
		public string tgc_nm { get; set; }
		public string tgc_ne { get; set; }
		public string cfm_nm { get; set; }
		public string ctc_nm { get; set; }
		public string ccv_nm { get; set; }
		public string cep_nm { get; set; }
		public string mfx_nm { get; set; }
		public string rif_nm { get; set; }
		public string amx_nm { get; set; }
		public string axs_nm { get; set; }
		public string amb_nm { get; set; }
		public string vor_nm { get; set; }
		public string vio_nm { get; set; }
		public string vam_nm { get; set; }
		public string pru_nm { get; set; }
		public string cpd_nm { get; set; }
		public string fdc_nm { get; set; }
		public string fdc_ne { get; set; }
		public string ctp_nm { get; set; }
		public string ctp_ne { get; set; }
		public string cza_nm { get; set; }
		public string cza_ne { get; set; }
		public string imr_nm { get; set; }
		public string imr_ne { get; set; }
		public string mev_nm { get; set; }
		public string mev_ne { get; set; }
		public string x_ilab_num { get; set; }
		public string x_depart { get; set; }
		public string x_starsnum { get; set; }
		public string x_receive { get; set; }
		public string x_hospadd { get; set; }
		public string x_name { get; set; }
		public string x_category { get; set; }
		public string x_suspect { get; set; }
		public string x_samdesc { get; set; }
		public string x_expr2 { get; set; }
		public DateTime? x_testdate { get; set; }
		public string x_reportno { get; set; }
		public string x_reportda { get; set; }
		public string x_approve { get; set; }
		public string x_analyst { get; set; }
		public string x_approver { get; set; }
		public string vana_pcr { get; set; }
		public string x_vanb { get; set; }
		public string x_vanc1 { get; set; }
		public string x_vanc2_c3 { get; set; }
		public string meca_pcr { get; set; }
		public string x_mecc { get; set; }
		public string x_blaimp { get; set; }
		public string x_blavim { get; set; }
		public string x_blaoxa { get; set; }
		public string x_blandm { get; set; }
		public string x_blapc { get; set; }
		public string x_mcr1 { get; set; }
		public string x_mcr2 { get; set; }
		public string x_mcr3 { get; set; }
		public string x_mcr4 { get; set; }
		public string x_mcr5 { get; set; }
		public string x_mcr6 { get; set; }
		public string x_mcr7 { get; set; }
		public string x_mcr8 { get; set; }
		public string x_mcr9 { get; set; }
		public string x_mcr10 { get; set; }
		public string x_amk_mic { get; set; }
		public string x_amk_ris { get; set; }
		public string x_amc_mic { get; set; }
		public string x_amc_ris { get; set; }
		public string x_amp_mic { get; set; }
		public string x_amp_ris { get; set; }
		public string x_sam_mic { get; set; }
		public string x_sam_ris { get; set; }
		public string x_azm_mic { get; set; }
		public string x_azm_ris { get; set; }
		public string x_fep_mic { get; set; }
		public string x_fep_ris { get; set; }
		public string x_ctx_mic { get; set; }
		public string x_ctx_ris { get; set; }
		public string x_fox_mic { get; set; }
		public string x_fox_ris { get; set; }
		public string x_caz_mic { get; set; }
		public string x_caz_ris { get; set; }
		public string x_cro_mic { get; set; }
		public string x_cro_ris { get; set; }
		public string x_cxm_mic { get; set; }
		public string x_cxm_ris { get; set; }
		public string x_chl_mic { get; set; }
		public string x_chl_ris { get; set; }
		public string x_cip_mic { get; set; }
		public string x_cip_ris { get; set; }
		public string x_cli_mic { get; set; }
		public string x_cli_ris { get; set; }
		public string x_col_mic { get; set; }
		public string x_col_ris { get; set; }
		public string x_cpo_mic { get; set; }
		public string x_cpo_sir { get; set; }
		public string x_czo_mic { get; set; }
		public string x_czo_sir { get; set; }
		public string x_cxa_mic { get; set; }
		public string x_cxa_sir { get; set; }
		public string x_csl_mic { get; set; }
		public string x_csl_sir { get; set; }
		public string x_dap_mic { get; set; }
		public string x_dap_ris { get; set; }
		public string x_dor_mic { get; set; }
		public string x_dor_ris { get; set; }
		public string x_etp_mic { get; set; }
		public string x_etp_ris { get; set; }
		public string x_ert_mic { get; set; }
		public string x_ert_ris { get; set; }
		public string x_ery_mic { get; set; }
		public string x_ery_ris { get; set; }
		public string x_fus_mic { get; set; }
		public string x_fus_sir { get; set; }
		public string x_fos_mic { get; set; }
		public string x_fos_sir { get; set; }
		public string x_geh_mic { get; set; }
		public string x_geh_ris { get; set; }
		public string x_gen_mic { get; set; }
		public string x_gen_ris { get; set; }
		public string x_ipm_mic { get; set; }
		public string x_ipm_ris { get; set; }
		public string x_lvx_mic { get; set; }
		public string x_lvx_ris { get; set; }
		public string x_lnz_mic { get; set; }
		public string x_lnz_ris { get; set; }
		public string x_mem_mic { get; set; }
		public string x_mem_ris { get; set; }
		public string x_mfx_mic { get; set; }
		public string x_mfx_ris { get; set; }
		public string x_net_mic { get; set; }
		public string x_net_ris { get; set; }
		public string x_oxa_mic { get; set; }
		public string x_oxa_ris { get; set; }
		public string x_pen_mic { get; set; }
		public string x_pen_ris { get; set; }
		public string x_TZP_mic { get; set; }
		public string x_tzp_ris { get; set; }
		public string x_rif_mic { get; set; }
		public string x_rif_ris { get; set; }
		public string x_sth_mic { get; set; }
		public string x_sth_ris { get; set; }
		public string x_tec_mic { get; set; }
		public string x_tec_ris { get; set; }
		public string x_tcy_mic { get; set; }
		public string x_tcy_ris { get; set; }
		public string x_tgc_mic { get; set; }
		public string x_tgc_ris { get; set; }
		public string x_sxt_mic { get; set; }
		public string x_sxt_ris { get; set; }
		public string x_van_mic { get; set; }
		public string x_van_ris { get; set; }
		public string species { get; set; }
		public string anim_type { get; set; }
		public string food { get; set; }
		public string market_cat { get; set; }
		public string brand { get; set; }
		public string breed { get; set; }
		public string date_expir { get; set; }
		public string farm_num { get; set; }
		public string sex_categ { get; set; }
		public string food_type { get; set; }
		public string spec_prov { get; set; }
		public string spec_dist { get; set; }
    }
}
